swagger: "2.0"
info:
  description: "This is the first draft of the API documentation for the backend of our RNA application"
  version: "1.0.0"
  title: "RNA Bioinformatics Platform to Accelerate Biomedical Research"
  # contact:
  #   email: "apiteam@swagger.io"
  # license:
  #   name: "Apache 2.0"
  #   url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "vm_ip_address_here"
basePath: "/v1"
tags:
- name: "BayesPairing"
  description: "Identifying RNA 3D modules in sequence and alignments"
  externalDocs:
    description: "Find out more"
    url: "http://bayespairing.cs.mcgill.ca/"
- name: "VeRNAl"
  description: "Fuzzy Recurrent Subgraph Mining"
  externalDocs:
    description: "Find out more"
    url: "http://vernal.cs.mcgill.ca/"
- name: "RNAmigos"
  description: "RNA Small Molecule Ligand Prediction"
  externalDocs:
    description: "Find out more"
    url: "http://rnamigos.cs.mcgill.ca/"
- name: "Pipeline"
  description: "Pipeline endpoints that combine the above three tools"
# schemes:
# - "https"
# - "http"
paths:
  /bayespairing:
    get:
      tags:
      - "BayesPairing"
      summary: "file input"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "description"
        required: true
        schema:
          $ref: "#/definitions/BayesPairingFileInput"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/BayesPairingOutput"
      # security:
      # - petstore_auth:
      #   - "write:pets"
      #   - "read:pets"
  /bayespairing/sequence:
    get:
      tags:
      - "BayesPairing"
      summary: "sequence input"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "description"
        required: true
        schema:
          $ref: "#/definitions/BayesPairingStringInput"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/BayesPairingOutput"
      # security:
      # - petstore_auth:
      #   - "write:pets"
      #   - "read:pets"
  /vernal:
    get:
      tags:
      - "VeRNAl"
      summary: "summary here"
      description: "description here"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "description"
        required: true
        schema:
          $ref: "#/definitions/VernalInput"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/VernalOutput"
  /rnamigos:
    get:
      tags:
      - "RNAmigos"
      summary: "summary here"
      description: "description here."
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "description"
        required: true
        schema:
          $ref: "#/definitions/RnamigosInput"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/RnamigosOutput"
  /pipeline:
    get:
      tags:
      - "Pipeline"
      summary: "file input"
      description: "Pipeline with BayesPairing file input."
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          type: object
          properties:
            vernal:
              type: "integer"
              enum: [0, 1]
              example: 0
              description: "whether to call VeRNAl in the Pipeline."
            rnamigos:
              type: "integer"
              enum: [0, 1]
              example: 1
              description: "whether to call RNAmigos in the Pipeline."
            threshold:
              type: "integer"
              default: 20
              description: "This describes the number of motifs returned by BayesPairing that are processed by VeRNAl and RNAmigos respectively. It is recommended to keep this at the default, as high values may incur significant overhead."
            params:
              $ref: "#/definitions/PipelineFileInput"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/PipelineOutput"
  /pipeline/sequence:
    get:
      tags:
      - "Pipeline"
      summary: "string input"
      description: "Pipeline with BayesPairing string input."
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          type: object
          properties:
            vernal:
              type: "integer"
              enum: [0, 1]
              example: 0
              description: "whether to call VeRNAl in the Pipeline."
            rnamigos:
              type: "integer"
              enum: [0, 1]
              example: 1
              description: "whether to call RNAmigos in the Pipeline."
            params:
              $ref: "#/definitions/PipelineStringInput"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/PipelineOutput"
# securityDefinitions:
#   petstore_auth:
#     type: "oauth2"
#     authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
#     flow: "implicit"
#     scopes:
#       write:pets: "modify pets in your account"
#       read:pets: "read your pets"
#   api_key:
#     type: "apiKey"
#     name: "api_key"
#     in: "header"
definitions:
  BayesPairingFileInput:
    type: object
    properties:
      sequence:
        type: "string"
        format: "binary"
        description: "FASTA file for a single or multiple sequences, or a Stockholm file for alignments."
      dataset:
        type: "string"
        format: "binary"
        description: "Specifies a BayesPairing dataset. This feature will not be available at launch and the default will always be used."
      advanced_settings:
        $ref: "#/definitions/BayesPairingFileSettings"
  BayesPairingFileSettings:
    type: object
    properties:
      secondary_structure:
        type: "string"
        description: "A single secondary structure provided as a string."
      secondary_structure_in_file:
        type: boolean
        description: "True if the secondary structure is included in the FASTA file."
        default: false
      sample_size:
        type: "integer"
        description: "Size of the structure sample."
        default: 20000
      score_threshold:
        type: "number"
        description: "Score threshold for a module to be called. [0 to 35]."
        default: -2.3
      window_length:
        type: "integer"
        description: "Window Length [50 to 300]."
        default: 200
      lambda:
        type: "number"
        description: "Weight of the secondary structure weight (lambda)."
        default: 0.35
      theta:
        type: number
        description: "Constant to multiply the sequence score by."
        default: 1
      delta:
        type: number
        description: "If you do not want to sample the whole secondary structure landscape, the maximum delta energy."
        default: -1
      constraints:
        type: number
        description: "RNAfold constraints on input sequence."      
        default: -1
      step_size:
        type: "integer"
        description: "Step size between windows [10 to 200]."
        default: 100
      pretrained:
        type: "boolean"
        description: "Indicates whether the provided model has already been trained"
        default: false
      vernal:
        type: "boolean"
        description: "will we run VeRNAl in the pipeline?"
        default: true
      rnamigos:
        type: "boolean"
        description: "will we run RNAmigos in the pipeline?"
        default: true
  BayesPairingStringInput:
    type: object
    properties:
      sequence:
        type: "string"
        description: "A single string sequence."
      dataset:
        type: "string"
        format: "binary"
        description: "Specifies a BayesPairing dataset. This feature will not be available at launch and the default will always be used."
      advanced_settings:
        $ref: "#/definitions/BayesPairingStringSettings"
  BayesPairingStringSettings:
    type: object
    properties:
      secondary_structure:
        type: "string"
        description: "A single secondary structure provided as a string."
      sample_size:
        type: "integer"
        description: "Size of the structure sample."
        default: 20000
      score_threshold:
        type: "number"
        description: "Score threshold for a module to be called. [0 to 35]."
        default: -2.3
      window_length:
        type: "integer"
        description: "Window Length [50 to 300]."
        default: 200
      lambda:
        type: "number"
        description: "Weight of the secondary structure weight (lambda)."
        default: 0.35
      theta:
        type: number
        description: "Constant to multiply the sequence score by."
        default: 1
      delta:
        type: number
        description: "If you do not want to sample the whole secondary structure landscape, the maximum delta energy."
        default: -1
      constraints:
        type: number
        description: "RNAfold constraints on input sequence."      
        default: -1
      step_size:
        type: "integer"
        description: "Step size between windows [10 to 200]."
        default: 100
      pretrained:
        type: "boolean"
        description: "Indicates whether the provided model has already been trained"
        default: false
      vernal:
        type: "boolean"
        description: "will we run VeRNAl in the pipeline?"
        default: true
      rnamigos:
        type: "boolean"
        description: "will we run RNAmigos in the pipeline?"
        default: true
  BayesPairingOutput:
    type: object
    properties:
      motifs:
        type: string
        format: "binary"
        description: "A pickle file consisting of all motifs above the given threshold."
      secondary_structure_svg:
        type: string
        format: "binary"
        description: "An SVG of the generated secondary structure."      
      secondary_strcture_data:
        type: "string"
        format: "binary"
        description: "A CSV that contains information on the motifs in the secondary structure SVG."
  VernalInput:
    type: object
    properties:
      id:
        type: string
      advanced_settings:
        $ref: "#/definitions/VernalSettings"
  VernalSettings:
    type: object
    properties:
      id:
        type: string
  VernalOutput:
    type: object
    properties:
      id:
        type: string
  RnamigosInput:
    type: object
    properties:
      RNA_binding_site_structure:
        type: "string"
        format: "binary"
        description: "file"
      type:
        type: "string"
        description: "file type, one of [...]" 
      ligand_library:
        type: "string"
        format: "binary"
        description: "file"
      advanced_settings:
        $ref: "#/definitions/RnamigosSettings"
  RnamigosSettings:
    type: "object"
    properties:
      parallel:
        type: "boolean"
        description: "description/explanation of the parameter"
      annotated_data:
        type: "string"
      batch_size:
        type: "integer"
        default: 8
      workers:
        type: "integer"
        default: 20
      name:
        type: "string"
        default: "default_name"
      num_epochs:
        type: "integer"
        default: 3
      fp_lam:
        type: "number"
        default: 1.0
      reconstruction_lam:
        type: "number"
        default: 1.0
      attributor_dims:
        type: "integer"
        default: [16,166]
      embedding_dims:
        type: "integer"
        default: [16,16,16]
      sim_function:
        type: "string"
        default: "R_1"
      embed_only:
        type: "integer"
        default: -1
      warm_start:
        type: "string"
      pos_weight:
        type: "integer"
        default: 0
      pool:
        type: "string"
        default: "sum"
      nucs:
        type: "boolean"
        default: True
      seed:
        type: "integer"
        default: 0
      kfold:
        type: "integer"
        default: 0
      early_stop:
        type: "integer"
        default: 10
      clustered:
        type: "boolean"
        default: False
      num_clusts:
        type: "integer"
        default: 8
  RnamigosOutput:
    type: object
    properties:
      id:
        type: string
  PipelineFileInput:
    type: object
    properties:
      bayespairing:
        $ref: "#/definitions/BayesPairingFileInput"
      vernal:
        $ref: "#/definitions/VernalInput"
      rnamigos:
        $ref: "#/definitions/RnamigosInput"
  PipelineStringInput:
    type: object
    properties:
      bayespairing:
        $ref: "#/definitions/BayesPairingStringInput"
      vernal:
        $ref: "#/definitions/VernalInput"
      rnamigos:
        $ref: "#/definitions/RnamigosInput"
  PipelineOutput:
    type: object
    properties:
      bayespairing:
        $ref: "#/definitions/BayesPairingOutput"
      similar_motifs:
        type: string
        format: "binary"
        description: "A pickle file containing a list of similar motifs to those returned by BayesPairing. This is the output of VeRNAl."
      ligands:
        type: string
        format: "binary"
        description: "A pickle file containing a list of ligands that tend to interact with the motifs returned by BayesPairing. This is the output of RNAmigos."
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
