swagger: "2.0"
info:
  description: "This is the first draft of the API documentation for the backend of our RNA application"
  version: "1.0.0"
  title: "RNA Bioinformatics Platform to Accelerate Biomedical Research"
  # contact:
  #   email: "apiteam@swagger.io"
  # license:
  #   name: "Apache 2.0"
  #   url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "vm_ip_address_here"
basePath: "/v1"
tags:
- name: "BayesPairing"
  description: "Identifying RNA 3D modules in sequence and alignments"
  externalDocs:
    description: "Find out more"
    url: "http://bayespairing.cs.mcgill.ca/"
- name: "VeRNAl"
  description: "Fuzzy Recurrent Subgraph Mining"
  externalDocs:
    description: "Find out more"
    url: "http://vernal.cs.mcgill.ca/"
- name: "RNAmigos"
  description: "RNA Small Molecule Ligand Prediction"
  externalDocs:
    description: "Find out more"
    url: "http://rnamigos.cs.mcgill.ca/"
- name: "Pipeline"
  description: "Pipeline endpoints that combine the above three tools"
# schemes:
# - "https"
# - "http"
paths:
  # BAYESPAIRING
  /bayespairing:
    get:
      tags:
      - "BayesPairing"
      summary: "file input"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "description"
        required: true
        schema:
          $ref: "#/definitions/BayesPairingFileInput"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/BayesPairingOutput"
      # security:
      # - petstore_auth:
      #   - "write:pets"
      #   - "read:pets"
  /bayespairing/sequence:
    get:
      tags:
      - "BayesPairing"
      summary: "single sequence string input"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "description"
        required: true
        schema:
          $ref: "#/definitions/BayesPairingStringInput"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/BayesPairingOutput"
      # security:
      # - petstore_auth:
      #   - "write:pets"
      #   - "read:pets"
  # VERNAL
  /vernal:
    get:
      tags:
      - "VeRNAl"
      summary: "summary here"
      description: "description here"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "description"
        required: true
        schema:
          $ref: "#/definitions/VernalInput"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/VernalOutput"
  # RNAMIGOS
  /rnamigos:
    get:
      tags:
      - "RNAmigos"
      summary: "summary here"
      description: "description here."
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "description"
        required: true
        schema:
          $ref: "#/definitions/RnamigosInput"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/RnamigosOutput"
  # PIPELINE
  /pipeline:
    get:
      tags:
      - "Pipeline"
      summary: "file input"
      description: "Pipeline with BayesPairing file input."
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          type: object
          properties:
            vernal:
              type: "integer"
              enum: [0, 1]
              example: 0
              description: "whether to call VeRNAl in the Pipeline."
            rnamigos:
              type: "integer"
              enum: [0, 1]
              example: 1
              description: "whether to call RNAmigos in the Pipeline."
            threshold:
              type: "integer"
              default: 20
              description: "This describes the number of motifs returned by BayesPairing that are processed by VeRNAl and RNAmigos respectively. It is recommended to keep this at the default, as high values may incur significant overhead."
            params:
              $ref: "#/definitions/PipelineFileInput"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/PipelineOutput"
  /pipeline/sequence:
    get:
      tags:
      - "Pipeline"
      summary: "string input"
      description: "Pipeline with BayesPairing string input."
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          type: object
          properties:
            vernal:
              type: "integer"
              enum: [0, 1]
              example: 0
              description: "whether to call VeRNAl in the Pipeline."
            rnamigos:
              type: "integer"
              enum: [0, 1]
              example: 1
              description: "whether to call RNAmigos in the Pipeline."
            params:
              $ref: "#/definitions/PipelineStringInput"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/PipelineOutput"
# securityDefinitions:
#   petstore_auth:
#     type: "oauth2"
#     authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
#     flow: "implicit"
#     scopes:
#       write:pets: "modify pets in your account"
#       read:pets: "read your pets"
#   api_key:
#     type: "apiKey"
#     name: "api_key"
#     in: "header"
definitions:
  BayesPairingFileInput:
    $ref: "./BayesPairing/BayesPairingFileInputSchema.yaml"
  BayesPairingStringInput:
    $ref: "./BayesPairing/BayesPairingStringInputSchema.yaml"
  BayesPairingOutput:
    $ref: "./BayesPairing/BayesPairingOutput.yaml"
  VernalInput:
    $ref: "./VeRNAl/VernalInputSchema.yaml"
  VernalOutput:
    $ref: "./VeRNAl/VernalOutputSchema.yaml"
  RnamigosInput:
    $ref: "./RNAmigos/RnamigosInputSchema.yaml"
  RnamigosOutput:    
    $ref: "./RNAmigos/RnamigosOutputSchema.yaml"
  PipelineFileInput:
    $ref: "./Pipeline/PipelineFileInputSchema.yaml"
  PipelineStringInput:
    $ref: "./Pipeline/PipelineStringInputSchema.yaml"
  PipelineOutput:
    $ref: "./Pipeline/PipelineOutputSchema.yaml"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
